# Generated by Django 2.2.10 on 2020-08-30 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0003_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
