# Generated by Django 2.2.10 on 2020-08-30 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0005_auto_20200830_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 30, 17, 20, 41, 25367, tzinfo=utc)),
        ),
    ]
