# Generated by Django 2.2.10 on 2020-08-30 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0010_auto_20200830_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
