# Generated by Django 2.2.10 on 2020-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0012_auto_20200901_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=128),
        ),
    ]
