# Generated by Django 2.2.10 on 2020-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
