# Generated by Django 2.2.10 on 2020-08-30 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0007_auto_20200830_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 17, 22, 13, 727387, tzinfo=utc)),
        ),
    ]
