# Generated by Django 2.2.10 on 2020-08-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistore', '0008_auto_20200830_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
